/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Clip } from "./Clip";
export type { Dog } from "./Dog";
export type { Vat } from "./Vat";
export * as factories from "./factories";
export { Clip__factory } from "./factories/Clip__factory";
export { Dog__factory } from "./factories/Dog__factory";
export { Vat__factory } from "./factories/Vat__factory";
